import RiyaahWEB from "../images/Project/riyaaah_web.webp";
import NeeedArchi from "../images/Project/neeedArchi.webp";
import EvDashboard from "../images/Project/OMI.webp";
import OrderManagement from "../images/ServiceLogo/modernWebsite.webp";
import HerKey from "../images/Project/herkey.webp";
import Centrum from "../images/Project/wealthverseweb.png";
import WealthVerseApp from "../images/Project/WealthVerseApp.png";
import Apexx from "../images/Project/apexx.svg";
import WhatsAppDoctor from "../images/Project/whatsappDoctor.png";
import WhatsAppInstitute from "../images/Project/whatsappInstitute.png";
import CryptoX from "../images/Project/crypto.webp";
import MetaMask from "../images/Project/metamask.webp";

export const allProjects = [
  {
    id: '01',
    category: 'WEBSITE',
    title: 'Riyaah E-Commerce',
    projectUrl: 'https://riyaah.sa/en',
    status: 'live',
    techStack: ['Next.js', 'CSS', 'Tailwind', 'Algolia','React Query'],
    Image: RiyaahWEB,
    highlight: 'E.',
    description: 'Multi-language e-commerce platform with Algolia-powered lightning-fast search and seamless English-Arabic support, delivering excellent UX for high-volume shoppers.',
    developmentType: 'Frontend',
    gridArea: 'span 2 / span 2', // Featured Item
    isBig: true,
    client:"Saudi Arabia",
    map:"image url",
  },
  {
    id: '02',
    category: 'WEBSITE',
    title: 'Order Management',
    projectUrl: 'https://riyaah-oms-prod.access.keurolife.com/',
    status: 'private',
    techStack: ['ReactJS', 'Tailwind', 'Algolia','React Query'],
    Image: "",
    highlight: 'P.',
    description: "Comprehensive admin panel for managing orders, product catalog, dynamic banners, and inventory optimizing Riyaah's backend workflows.",
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"Saudi Arabia",
    map:"image url",
    bgColor:"#fdf0f0"
  },
  {
    id: '03',
    category: 'WEBSITE',
    title: 'EV-Ready Dashboard',
    projectUrl: 'https://evreadyindia.org/',
    status: 'private',
    techStack: ['NextJS', 'CSS', 'Tailwind'],
    Image: EvDashboard,
    highlight: 'C.',
    description: 'Interactive dashboard visualizing EV ecosystem metrics across states, empowering government stakeholders with data-driven policy insights.',
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"India",
    map:"image url",
    bgColor:"#00020A"
  },
  {
    id: '04',
    category: 'PWA',
    title: 'HerKey',
    projectUrl: 'https://www.herkey.com/',
    status: 'live',
    techStack: ['ReactJS', 'CSS', 'Tailwind'],
    Image: HerKey,
    highlight: 'B.',
    description: 'Progressive Web App designed for women professionals focusing on job matching and mentorship with offline-first architecture and top Lighthouse scores.',
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"India",
    map:"image url",
    bgColor:"#925070"
  },
  {
    id: '05',
    category: 'WEBSITE',
    title: 'Centrum Wealthverse',
    projectUrl: 'https://wealthverse.centrumwealth.co.in',
    status: 'private',
    techStack: ['ReactJS','Tailwind','Redux'],
    Image: Centrum,
    highlight: 'T.',
    description: 'Fintech platform offering real-time investment tracking, portfolio management, and wealth analytics with performance-optimized code splitting.',
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"India",
    map:"image url",
    bgColor: "black"
  },
  {
    id: '06',
    category: 'APP',
    title: 'Wealthverse Mobile',
    projectUrl: 'https://apps.apple.com/in/app/wealthverse/id6443810791',
    status: 'private',
    techStack: ['React-Native','Redux'],
    Image: WealthVerseApp,
    highlight: 'S.',
    description: 'Mobile app providing seamless wealth management and investment monitoring on-the-go, built using React Native for native performance.',
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"India",
    map:"image url"
  },
  {
    id: '07',
    category: 'WEBSITE',
    title: 'Apexx',
    projectUrl: '',
    status: 'private',
    techStack: ['ReactJS','SCSS', 'Jest', 'React Testing Library'],
    Image: Apexx,
    highlight: 'F.',
    description: 'Internal payment system dashboard for high-volume transactions with real-time data visualization, enhancing payment monitoring efficiency.',
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"London",
    map:"image url"
  },
  {
    id: '08',
    category: 'APP',
    title: 'WhatsApp Doctor Appointment Agent',
    projectUrl: '',
    status: 'private',
    techStack: ['WhatsApp Cloud API', 'NextJS', 'Supabase', 'Google Calendar API', 'Google Sheets API'],
    Image: WhatsAppDoctor,
    highlight: 'C.',
    description: 'WhatsApp appointment system: patients book, cancel and rebook in chat with live slots, doctors onboard, block time and send prescription PDFs, with an admin dashboard and Google Calendar and Sheets sync.',
    developmentType: 'Full Stack',
    gridArea: 'span 1 / span 2',
    isBigNumber: true,
    client:"India",
    map:"image url",
    bgColor: "#0a0a0c"
  },
  {
    id: '09',
    category: 'APP',
    title: 'WhatsApp Course Enquiry Agent',
    projectUrl: '',
    status: 'private',
    techStack: ['WhatsApp Cloud API', 'NextJS', 'Supabase', 'AI/LLM API'],
    Image: WhatsAppInstitute,
    highlight: 'W.',
    description: 'WhatsApp agent for an engineering institute: students browse 66 courses in 6 categories, get AI answers, register and request enrollment, with an admin panel to verify payments and issue coupons.',
    developmentType: 'Full Stack',
    gridArea: 'span 1 / span 1',
    client:"India",
    map:"image url",
    bgColor: "#0a0a0c"
  },
  {
    id: '10',
    category: 'WEBSITE',
    title: 'Neeed Architecture',
    projectUrl: 'https://architecture.neeedassociates.com/',
    status: 'live',
    techStack: ['ReactJS', 'Tailwind','Replicate'],
    Image: NeeedArchi,
    highlight: 'N.',
    description: 'Architectural firm website showcasing project portfolios with responsive design and fluid user experience.',
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"India",
    map:"image url",
    bgColor:"#ffffff"
  },
  {
    id: '11',
    category: 'APP',
    title: 'CryptoX Trading',
    projectUrl: '',
    status: 'private',
    techStack: ['React-Native', 'Redux', 'WebSockets'],
    Image: CryptoX,
    highlight: 'X.',
    description: 'Real-time cryptocurrency trading app delivering live price updates, interactive candlestick charts, and secure trade execution.',
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"Canada",
    map:"image url",
    bgColor:"#151418"
  },
  {
    id: '12',
    category: 'EXTENSION',
    title: 'MetaMask Clone',
    projectUrl: '',
    status: 'private',
    techStack: ['ReactJS', 'Web3.js','metaMask'],
    Image: MetaMask,
    highlight: 'E.',
    description: 'Ethereum wallet browser extension supporting seamless DApp integration, private key encryption, and multi-cryptocurrency support.',
    developmentType: 'Frontend',
    gridArea: 'span 1 / span 1',
    client:"Canada",
    map:"image url",
    bgColor:"#F48929"
  }
];
